# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ecn_mobile.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ecn_mobile.proto',
  package='id.ac.itb.pptik.ecn',
  syntax='proto3',
  serialized_pb=_b('\n\x10\x65\x63n_mobile.proto\x12\x13id.ac.itb.pptik.ecn\"\x91\x01\n\x0cMobileStream\x12\x12\n\nstation_id\x18\x01 \x01(\r\x12\x11\n\tsignature\x18\x02 \x01(\x0c\x12\x12\n\nstart_time\x18\x03 \x01(\x04\x12\x13\n\x0bsample_rate\x18\x04 \x01(\x05\x12\x0f\n\x07\x61\x63\x63\x65l_z\x18\x05 \x03(\x02\x12\x0f\n\x07\x61\x63\x63\x65l_n\x18\x06 \x03(\x02\x12\x0f\n\x07\x61\x63\x63\x65l_e\x18\x07 \x03(\x02\x62\x06proto3')
)




_MOBILESTREAM = _descriptor.Descriptor(
  name='MobileStream',
  full_name='id.ac.itb.pptik.ecn.MobileStream',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='station_id', full_name='id.ac.itb.pptik.ecn.MobileStream.station_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signature', full_name='id.ac.itb.pptik.ecn.MobileStream.signature', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start_time', full_name='id.ac.itb.pptik.ecn.MobileStream.start_time', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sample_rate', full_name='id.ac.itb.pptik.ecn.MobileStream.sample_rate', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='accel_z', full_name='id.ac.itb.pptik.ecn.MobileStream.accel_z', index=4,
      number=5, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='accel_n', full_name='id.ac.itb.pptik.ecn.MobileStream.accel_n', index=5,
      number=6, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='accel_e', full_name='id.ac.itb.pptik.ecn.MobileStream.accel_e', index=6,
      number=7, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=187,
)

DESCRIPTOR.message_types_by_name['MobileStream'] = _MOBILESTREAM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MobileStream = _reflection.GeneratedProtocolMessageType('MobileStream', (_message.Message,), dict(
  DESCRIPTOR = _MOBILESTREAM,
  __module__ = 'ecn_mobile_pb2'
  # @@protoc_insertion_point(class_scope:id.ac.itb.pptik.ecn.MobileStream)
  ))
_sym_db.RegisterMessage(MobileStream)


# @@protoc_insertion_point(module_scope)
